services:
  central-app:
    build:
      context: .
      dockerfile: CentralApp/Dockerfile
    image: central-app:latest
    container_name: central-app
    volumes:
      - ./test:/app/tests
    networks:
      - spring-net
    environment:
      - APP_UID=1000
      - WORKER_NODE_URL=http://worker-node-app:8080
    depends_on:
      - worker-node-app

  worker-node-app:
    build:
      context: .
      dockerfile: WorkerNodeApp/Dockerfile
    image: worker-node-app:latest
    container_name: worker-node-app
    volumes:
      - ./test:/app/tests
    networks:
      - spring-net
    environment:
      - APP_UID=1000

networks:
  spring-net:
    driver: bridge
